regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
blocklist:
  - "538023924079"  # Never nuke the root/production account
no-blocklist-terms-default: true
accounts:
  "144704597187":
    filters:
      IAMRole:
        - "*Organization*"
      S3Bucket:
        - type: contains
          value: cloudtrail
        - type: contains
          value: transfer
        - type: contains
          value: archive
      S3BucketObject:
        - type: contains
          value: 5-8-2025
        - type: regex
          value: (?i)backup
        - type: regex
          value: (?i)donotdelete
      CloudFormationStack:
        - type: regex
          value: (?i)crowdstrike
        - type: regex
          value: (?i)controltower
      CloudTrailTrail:
        - type: regex
          value: (?i)controltower
      ConfigServiceDeliveryChannel:
        - type: regex
          value: (?i)controltower
      ConfigServiceConfigurationRecorder:
        - type: regex
          value: (?i)controltower
      SNSTopic:
        - type: regex
          value: (?i)controltower
      SNSSubscription:
        - type: regex
          value: (?i)controltower
      CloudWatchEventsRule:
        - type: regex
          value: (?i)controltower
      CloudWatchEventsTarget:
        - type: regex
          value: (?i)controltower
      CloudWatchLogsLogGroup:
        - type: regex
          value: (?i)controltower
      LambdaFunction:
        - type: regex
          value: (?i)controltower
    # Add more resource filters as needed
