regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
blocklist:
  - "538023924079"  # Never nuke the root/production account
accounts:
  "825390673649":
    filters:
      IAMRole:
        - "*Organization*"
      S3Bucket:
        - type: contains
          value: cloudtrail
      CloudFormationStack:
        - type: regex
          value: (?i)controltower
      CloudTrailTrail:
        - type: regex
          value: (?i)controltower
    # Add more resource filters as needed
